version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    volumes:
      - my-lms-storage:/mnt/data
    environment:
      - FLASK_ENV=development
volumes:
  my-lms-storage:
    external: true